packages:
  - apps/*
  - packages/*

catalogs:
  build:
    '@rollup/plugin-babel': ^6.0.4
    rolldown-vite: 7.2.2
    tsdown: 0.16.1
  cli:
    '@changesets/changelog-github': ^0.5.0
    '@changesets/cli': ^2.27.9
  dev:
    '@babel/core': ^7.26.0
    '@babel/plugin-transform-runtime': 7.28.3
    '@babel/preset-env': 7.28.3
    '@babel/preset-typescript': ^7.27.1
    '@internationalized/date': ^3.9.0
    '@tailwindcss/vite': ^4.1.13
    '@vitejs/plugin-vue': ^6.0.1
    '@vue/tsconfig': ^0.8.1
    cac: ^6.7.14
    chrome-types: 0.1.321
    clsx: 2.1.1
    happy-dom: ^13.10.1
    tailwind-merge: 3.3.1
    tailwind-variants: ^3.1.1
    tailwindcss: ^4.1.13
    tw-animate-css: 1.4.0
    typescript: ^5.8.3
  i18n:
    i18next: ^23.16.4
  lint:
    '@eslint/js': ^9.27.0
    eslint: ^9.27.0
    husky: ^9.1.7
    lint-staged: ^16.1.0
    prettier: ^3.3.3
    typescript-eslint: ^8.32.1
  markdown:
    mdast-util-to-markdown: ^2.1.2
  monorepo:
    turbo: 2.5.8
  network:
    browser-fs-access: ^0.35.0
  node:
    '@babel/preset-env': ^7.26.0
    execa: ^9.5.1
    glob: ^10.4.5
  prod:
    '@babel/runtime': 7.28.3
    '@tanstack/vue-query': ^5.90.2
    '@vee-validate/zod': 4.15.1
    '@vueuse/core': 13.9.0
    '@zip.js/zip.js': ^2.7.53
    class-variance-authority: ^0.7.1
    core-js: 3.36.0
    es-toolkit: 1.39.10
    filenamify: ^6.0.0
    hast-util-to-html: ^9.0.5
    js-base64: ^3.7.7
    lucide-vue-next: ^0.544.0
    mdast-util-gfm-strikethrough: ^2.0.0
    mdast-util-gfm-table: ^2.0.0
    mdast-util-gfm-task-list-item: ^2.0.0
    mdast-util-math: ^3.0.0
    mdast-util-to-hast: ^13.2.0
    radash: ^12.1.0
    reka-ui: 2.5.1
    serialize-error: ^12.0.0
    tslib: ^2.8.1
    vee-validate: 4.15.1
    vue: ^3.5.22
    vue-i18n: 12.0.0-alpha.3
    vue-router: ^4.5.1
    zod: 4.1.11
  test:
    vitest: ^1.6.0
  tools:
    vue-tsc: ^3.1.0
    web-ext: 8.9.0
  types:
    '@types/lodash-es': ^4.17.12
    '@types/mdast': ^4.0.4
    '@types/node': 22.12.0
    '@types/regexp.escape': 2.0.0
  utils:
    lodash-es: ^4.17.21
    regexp.escape: 2.0.1
